# Generated by Django 5.1.4 on 2025-01-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        ('users', '0014_alter_user_info_pfp'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs_info',
            name='owner',
            field=models.CharField(default='owner', max_length=20),
        ),
        migrations.AlterField(
            model_name='clubs_info',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='clubs', to='users.user_info'),
        ),
        migrations.AlterField(
            model_name='clubs_info',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
