# Generated by Django 5.1.4 on 2025-01-05 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_clubs_info_owner_alter_clubs_info_members_and_more'),
        ('users', '0014_alter_user_info_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs_info',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_clubs', to='users.user_info'),
        ),
    ]
