# Generated by Django 5.1.4 on 2025-01-05 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_alter_clubs_info_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubs_info',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
