# Generated by Django 5.1.4 on 2025-01-05 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_rename_owner_clubs_info_owner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubs_info',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
