# Generated by Django 5.0.3 on 2025-01-06 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_rename_owner_id_clubs_info_owner'),
        ('users', '0014_alter_user_info_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs_info',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_clubs', to='users.user_info'),
        ),
    ]
