# Generated by Django 5.0.3 on 2025-01-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_alter_clubs_info_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs_info',
            name='slug',
            field=models.SlugField(default='/', unique=True),
        ),
    ]
