# Generated by Django 5.1.4 on 2025-01-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0008_alter_clubs_info_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs_info',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
