# Generated by Django 5.1.4 on 2025-01-16 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_comments'),
        ('users', '0014_alter_user_info_pfp'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='club_comments', to='clubs.clubs_info'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.user_info'),
        ),
    ]
