# Generated by Django 5.1.4 on 2025-01-18 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0014_alter_user_info_pfp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('last_date', models.DateField()),
                ('rules', models.TextField()),
                ('participants', models.ManyToManyField(related_name='events', to='users.user_info')),
            ],
        ),
    ]
