# Generated by Django 5.1.4 on 2024-12-31 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_info_gmail_alter_user_info_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='last_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user_info',
            name='pfp',
            field=models.ImageField(default='static/images/deafult.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='username',
            field=models.CharField(max_length=7),
        ),
    ]
