# Generated by Django 5.1.4 on 2024-12-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_info_last_name_user_info_pfp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='pfp',
            field=models.ImageField(default='HomePage/static/images/deafult.jpg', upload_to=''),
        ),
    ]
