# Generated by Django 5.0.3 on 2024-12-31 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_info_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='last_name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='pfp',
            field=models.ImageField(default='static/images/defaultpfp.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='username',
            field=models.CharField(max_length=15),
        ),
    ]
