# Generated by Django 5.0.3 on 2025-01-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_info_is_anonymous_alter_user_info_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_info',
            options={},
        ),
        migrations.AlterModelManagers(
            name='user_info',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='is_anonymous',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='user_info',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='username',
            field=models.CharField(max_length=15),
        ),
    ]
