# Generated by Django 5.0.3 on 2025-01-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_username_user_info_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='password',
        ),
        migrations.AddField(
            model_name='user_info',
            name='username',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
