# Generated by Django 5.1.4 on 2025-01-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_user_info_last_name_remove_user_info_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
