# Generated by Django 5.1.4 on 2025-01-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_info_password_alter_user_info_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='pfp',
            field=models.ImageField(default='../../static/images/defaultpfp.jpg', upload_to=''),
        ),
    ]
