# Generated by Django 5.1.4 on 2025-01-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_info_pfp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='premmision',
            field=models.BooleanField(default=False),
        ),
    ]
